import { useEffect, useState } from "react";
import { Bell, Check, CreditCard, Database, LoaderCircle, LogOut, Moon, Palette, Shield, Sun, User } from "lucide-react";
import { Link } from "react-router-dom";
import { useNavigate } from "react-router-dom";
import { useAuthStore } from "@/stores/auth/authStore";
import { changePassword, getSettings, updateProfile, updateSettings } from "@/services/settings";
import { getImages, getVideos } from "@/services/media";
import api from "@/services/api";

const sections=[{id:"profile",title:"Profile",icon:User},{id:"appearance",title:"Appearance",icon:Palette},{id:"notifications",title:"Notifications",icon:Bell},{id:"security",title:"Security",icon:Shield},{id:"storage",title:"Storage",icon:Database},{id:"usage",title:"Usage & billing",icon:CreditCard}];
const fieldClass="mt-2 h-11 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 text-sm text-white outline-none focus:border-violet-500";
const applyTheme = (theme) => { document.documentElement.dataset.theme = theme; };

export default function Settings(){
 const [active,setActive]=useState("profile");const [settings,setSettings]=useState(null);const [usage,setUsage]=useState(null);const [billing,setBilling]=useState({balance:null,transactions:[],packages:[],payments:[]});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("");const [error,setError]=useState("");const user=useAuthStore(s=>s.user);const setUser=useAuthStore(s=>s.setUser);const logout=useAuthStore(s=>s.logout);const navigate=useNavigate();
 useEffect(()=>{let live=true;(async()=>{try{const [prefs,images,videos]=await Promise.all([getSettings(),getImages(),getVideos()]);if(live){setSettings(prefs);applyTheme(prefs.theme==="light"?"light":"dark");setUsage({images,videos});}}catch(e){if(live)setError(e.response?.data?.message||"Could not load your account settings.");}finally{if(live)setLoading(false);}})();return()=>{live=false};},[]);
 useEffect(()=>{let live=true;(async()=>{try{const [credits,packages,payments]=await Promise.all([api.get("/credits"),api.get("/billing/packages"),api.get("/billing/history")]);if(live)setBilling({balance:credits.data?.data?.balance??0,transactions:credits.data?.data?.transactions??[],packages:packages.data?.data?.packages??[],payments:payments.data?.data??[]});const reference=new URLSearchParams(window.location.search).get("reference");if(reference){const verified=await api.get(`/billing/verify/${encodeURIComponent(reference)}`);if(live){setNotice(verified.data?.data?.status==="success"?"Payment confirmed and credits added.":"Payment is still pending; your credits will appear after confirmation.");const updated=await api.get("/credits");setBilling(current=>({...current,balance:updated.data?.data?.balance??current.balance,transactions:updated.data?.data?.transactions??current.transactions}));}window.history.replaceState({},"",window.location.pathname);}}catch(e){if(live&&e.response?.status!==503)setError(e.response?.data?.message||"Could not load billing information.");}})();return()=>{live=false};},[]);
 const buyCredits=async(packageKey)=>{setSaving(true);setError("");try{const response=await api.post("/billing/initialize",{packageKey});window.location.assign(response.data.data.authorizationUrl);}catch(e){setError(e.response?.data?.message||"Could not start Paystack checkout.");setSaving(false);}};
 const savePrefs=async(changes)=>{setSaving(true);setNotice("");setError("");try{const next=await updateSettings(changes);setSettings(next);if(changes.theme)applyTheme(changes.theme);setNotice("Settings saved.");}catch(e){setError(e.response?.data?.message||"Could not save this setting.");}finally{setSaving(false);}};
 const saveName=async(event)=>{event.preventDefault();const name=new FormData(event.currentTarget).get("name");setSaving(true);setError("");setNotice("");try{const updated=await updateProfile({name});setUser(updated);setNotice("Profile saved.");}catch(e){setError(e.response?.data?.message||"Could not save your profile.");}finally{setSaving(false);}};
 const savePassword=async(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);if(form.get("newPassword")!==form.get("confirmPassword")){setError("The new passwords do not match.");return;}setSaving(true);setError("");setNotice("");try{await changePassword({currentPassword:form.get("currentPassword"),newPassword:form.get("newPassword")});event.currentTarget.reset();setNotice("Password updated.");}catch(e){setError(e.response?.data?.message||"Could not update your password.");}finally{setSaving(false);}};
 const signOut=async()=>{await logout();navigate("/login",{replace:true});};
 return <div className="space-y-7 text-white"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-violet-400">Account</p><h1 className="mt-2 text-3xl font-semibold">Settings</h1><p className="mt-2 text-sm text-zinc-500">Manage your profile, preferences, and account security.</p></div><button onClick={() => window.dispatchEvent(new Event("nebula:replay-onboarding"))} className="rounded-xl border border-zinc-700 px-4 py-2.5 text-sm text-zinc-300 hover:bg-zinc-800">Replay product tour</button></header>
 {notice&&<p role="status" className="flex items-center gap-2 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-3 text-sm text-emerald-300"><Check size={16}/>{notice}</p>}{error&&<p role="alert" className="rounded-xl border border-red-500/20 bg-red-500/5 p-3 text-sm text-red-300">{error}</p>}
 <div className="grid gap-5 lg:grid-cols-[230px_minmax(0,1fr)]"><nav className="flex gap-2 overflow-x-auto lg:flex-col">{sections.map(({id,title,icon:Icon})=><button key={id} onClick={()=>setActive(id)} className={`flex shrink-0 items-center gap-3 rounded-xl px-4 py-3 text-left text-sm ${active===id?"bg-violet-600 text-white":"bg-zinc-900 text-zinc-400 hover:text-white"}`}><Icon size={17}/>{title}</button>)}</nav>
 <section className="min-h-[420px] rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5 sm:p-7">{loading?<div className="flex justify-center py-20 text-zinc-500"><LoaderCircle className="animate-spin"/></div>:<>
 {active==="profile"&&<><SectionTitle title="Profile" subtitle="Your account identity and sign-in email."/><form onSubmit={saveName} className="max-w-xl space-y-5"><label className="block text-sm text-zinc-400">Name<input name="name" required maxLength={100} defaultValue={user?.name||""} className={fieldClass}/></label><label className="block text-sm text-zinc-400">Email address<input value={user?.email||""} readOnly className={`${fieldClass} text-zinc-500`}/><span className="mt-1 block text-xs text-zinc-600">Contact support to change your sign-in email.</span></label><button disabled={saving} className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-medium disabled:opacity-50">{saving?"Saving…":"Save profile"}</button></form><div className="mt-10 border-t border-zinc-800 pt-5"><button onClick={signOut} className="inline-flex items-center gap-2 rounded-xl border border-zinc-700 px-4 py-2.5 text-sm text-zinc-300 hover:bg-zinc-800"><LogOut size={16}/> Sign out</button></div></>}
 {active==="appearance"&&<><SectionTitle title="Appearance" subtitle="Choose the theme for your Nebula workspace."/><div className="grid max-w-xl grid-cols-2 gap-3">{[{id:"dark",title:"Dark",icon:Moon},{id:"light",title:"Light",icon:Sun}].map(({id,title,icon:Icon})=><button key={id} onClick={()=>savePrefs({theme:id})} disabled={saving} className={`flex items-center gap-3 rounded-xl border p-4 ${settings?.theme===id?"border-violet-500 bg-violet-500/10":"border-zinc-800 bg-zinc-950"}`}><Icon size={18}/>{title}{settings?.theme===id&&<Check size={16} className="ml-auto text-violet-300"/>}</button>)}</div><p className="mt-4 text-xs text-zinc-600">Preference is saved to your account.</p></>}
 {active==="notifications"&&<><SectionTitle title="Notifications" subtitle="These preferences are saved to your account."/><div className="max-w-xl divide-y divide-zinc-800">{[{key:"emailNotifications",title:"Email notifications",description:"Product updates and account notices."},{key:"pushNotifications",title:"In-app notifications",description:"Updates while using Nebula AI Studio."}].map(({key,title,description})=><div key={key} className="flex items-center justify-between gap-5 py-5"><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-zinc-500">{description}</p></div><button role="switch" aria-checked={Boolean(settings?.[key])} disabled={saving} onClick={()=>savePrefs({[key]:!settings?.[key]})} className={`relative h-6 w-11 shrink-0 rounded-full ${settings?.[key]?"bg-violet-600":"bg-zinc-700"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition-all ${settings?.[key]?"left-6":"left-1"}`}/></button></div>)}</div></>}
 {active==="security"&&<><SectionTitle title="Security" subtitle="Change the password used to sign in."/><form onSubmit={savePassword} className="max-w-xl space-y-4">{[{name:"currentPassword",label:"Current password"},{name:"newPassword",label:"New password"},{name:"confirmPassword",label:"Confirm new password"}].map(({name,label})=><label key={name} className="block text-sm text-zinc-400">{label}<input name={name} required minLength={name==="currentPassword"?undefined:6} type="password" autoComplete={name==="currentPassword"?"current-password":"new-password"} className={fieldClass}/></label>)}<button disabled={saving} className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-medium disabled:opacity-50">{saving?"Updating…":"Update password"}</button></form></>}
 {active==="storage"&&<><SectionTitle title="Storage" subtitle="Media currently saved in your account."/><div className="grid max-w-xl gap-3 sm:grid-cols-2"><UsageCard label="Saved images" value={usage?.images?.length??0}/><UsageCard label="Saved videos" value={usage?.videos?.length??0}/></div><div className="mt-5 flex flex-wrap gap-3"><Link to="/images" className="rounded-xl border border-zinc-700 px-4 py-2.5 text-sm text-zinc-200 hover:bg-zinc-800">Manage images</Link><Link to="/videos" className="rounded-xl border border-zinc-700 px-4 py-2.5 text-sm text-zinc-200 hover:bg-zinc-800">Manage videos</Link></div><p className="mt-5 max-w-xl text-xs leading-5 text-zinc-600">This deployment does not track a cloud storage quota yet. These totals reflect records saved in the workspace database.</p></>}
 {active==="usage"&&<><SectionTitle title="Usage & billing" subtitle="Live usage, active AI providers, credits, and payments."/><div className="grid gap-3 sm:grid-cols-3"><UsageCard label="Images generated" value={usage?.images?.length??0}/><UsageCard label="Videos generated" value={usage?.videos?.length??0}/><UsageCard label="Credit balance" value={billing.balance??"—"}/></div><div className="mt-6 space-y-3"><ProviderCard type="Image generation" model="FLUX.2 Pro" id="black-forest-labs/flux-2-pro" platform="Replicate" count={usage?.images?.length??0}/><ProviderCard type="Video generation" model="Wan 2.6 I2V Flash" id="wan2.6-i2v-flash" platform="Alibaba Cloud · DashScope" count={usage?.videos?.length??0}/></div><div className="mt-6 rounded-xl border border-zinc-800 bg-zinc-950 p-4"><h3 className="font-medium">Buy credits <span className="text-xs text-zinc-500">Paystack test mode · minimum ₦10,000</span></h3>{billing.packages.length?<div className="mt-4 grid gap-3 sm:grid-cols-2">{billing.packages.map(item=><article key={item.key} className="rounded-xl border border-zinc-800 p-4"><p className="font-medium">{item.name||item.key}</p><p className="mt-2 text-sm text-zinc-400">{item.credits.toLocaleString()} credits · ₦{item.priceNgn.toLocaleString("en-NG")}</p><button disabled={saving} onClick={()=>buyCredits(item.key)} className="mt-4 rounded-lg bg-violet-600 px-4 py-2 text-sm disabled:opacity-50">{saving?"Opening checkout…":"Continue to Paystack"}</button></article>)}</div>:<p className="mt-3 text-sm leading-6 text-zinc-500">No packages are enabled yet. Set CREDIT_PACKAGES_JSON after reviewing provider cost, exchange rate, fees, and tax assumptions. No unverified credit-to-naira rate is being sold.</p>}</div><div className="mt-6"><h3 className="mb-3 font-medium">Credit activity</h3><div className="space-y-2">{billing.transactions.length?billing.transactions.map(item=><div key={item.id} className="flex justify-between gap-4 rounded-lg border border-zinc-800 px-3 py-2 text-sm"><span className="text-zinc-400">{item.reason}</span><span className={item.delta>0?"text-emerald-300":"text-zinc-200"}>{item.delta>0?"+":""}{item.delta}</span></div>):<p className="text-sm text-zinc-500">No credit activity yet.</p>}</div></div><div className="mt-6"><h3 className="mb-3 font-medium">Payment history</h3><div className="space-y-2">{billing.payments.length?billing.payments.map(item=><div key={item.id} className="flex flex-wrap justify-between gap-3 rounded-lg border border-zinc-800 px-3 py-2 text-sm"><span className="text-zinc-400">{item.packageKey} · {new Date(item.createdAt).toLocaleDateString()}</span><span>{item.status} · ₦{(item.amountMinor/100).toLocaleString("en-NG")}</span></div>):<p className="text-sm text-zinc-500">No payments yet.</p>}</div></div></>}
 </>}</section></div></div>;
}
function SectionTitle({title,subtitle}){return <div className="mb-6 border-b border-zinc-800 pb-5"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-zinc-500">{subtitle}</p></div>;}
function UsageCard({label,value}){return <div className="rounded-xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-sm text-zinc-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>;}
function ProviderCard({type,model,id,platform,count}){return <article className="flex flex-col gap-3 rounded-xl border border-zinc-800 bg-zinc-950 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="text-xs text-zinc-500">{type}</p><p className="mt-1 font-medium">{model}</p><p className="mt-1 break-all text-xs text-zinc-600">{id} · {platform}</p></div><span className="text-sm text-zinc-400">{count} saved generations</span></article>;}
