import { useEffect, useState } from "react";
import { Check, CreditCard, LoaderCircle, Wallet } from "lucide-react";
import api from "@/services/api";

const money = (minor, currency = "NGN") => new Intl.NumberFormat(undefined, { style: "currency", currency }).format(Number(minor || 0) / 100);

export default function Billing() {
  const [balance, setBalance] = useState(null); const [transactions, setTransactions] = useState([]); const [packages, setPackages] = useState([]); const [payments, setPayments] = useState([]); const [billingMode, setBillingMode] = useState("test"); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { let live = true; (async () => { try { const [c, p, h] = await Promise.all([api.get("/credits"), api.get("/billing/packages"), api.get("/billing/history")]); if (live) { setBalance(c.data?.data?.balance ?? 0); setTransactions(c.data?.data?.transactions ?? []); setPackages(p.data?.data?.packages ?? []); setPayments(h.data?.data ?? []); setBillingMode(p.data?.data?.mode || "test"); } const reference = new URLSearchParams(location.search).get("reference"); if (reference) { const verified = await api.get(`/billing/verify/${encodeURIComponent(reference)}`); if (live) setNotice(verified.data?.data?.status === "success" ? "Payment confirmed. Your credits are ready." : "Payment is pending confirmation."); history.replaceState({}, "", location.pathname); } } catch (e) { if (live) setError(e.response?.data?.message || "Billing information could not be loaded."); } finally { if (live) setLoading(false); } })(); return () => { live = false; }; }, []);
  const purchase = async (item) => { setBusy(item.key); setError(""); try { const response = await api.post("/billing/initialize", { packageKey: item.key }); window.location.assign(response.data.data.authorizationUrl); } catch (e) { setError(e.response?.data?.message || "Checkout could not be started."); setBusy(""); } };
  return <div className="space-y-8 text-white"><header><p className="text-sm text-violet-400">Account</p><h1 className="mt-2 text-3xl font-semibold">Credits & Billing</h1><p className="mt-2 text-sm text-zinc-500">Track credit usage, purchase configured packages, and review payments.</p></header>
    {notice && <p role="status" className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-3 text-sm text-emerald-300">{notice}</p>}{error && <p role="alert" className="rounded-xl border border-red-500/20 bg-red-500/5 p-3 text-sm text-red-300">{error}</p>}<p className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-sm text-amber-200">Payments are currently in Paystack {billingMode} mode. {billingMode === "test" ? "Test transactions do not collect real money." : "Checkout opens Paystack securely."}</p>
    {loading ? <div className="flex justify-center py-20 text-zinc-500"><LoaderCircle className="animate-spin"/></div> : <>
      <section data-tour="billing-balance" className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-violet-500/20 bg-gradient-to-br from-violet-950/60 to-zinc-900 p-6"><div className="flex items-center gap-2 text-sm text-zinc-400"><Wallet size={17}/> Available credits</div><p className="mt-4 text-4xl font-semibold">{balance ?? 0}</p><p className="mt-2 text-xs text-zinc-500">Credits are deducted when generation completes.</p></div><div className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-6 md:col-span-2"><h2 className="font-medium">How billing works</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Your balance includes free credits and purchased credits. Each generation shows its credit cost before you start. Payments are processed securely by Paystack; successful payments add credits to your account.</p></div></section>
      <section><div className="mb-4"><h2 className="text-xl font-semibold">Credit packages</h2><p className="mt-1 text-sm text-zinc-500">Choose from the packages available for this account.</p></div>{packages.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{packages.map((item, index) => <article key={item.key} className={`rounded-2xl border p-5 ${index === 0 ? "border-violet-500/50 bg-violet-500/5" : "border-zinc-800 bg-zinc-900/50"}`}><div className="flex items-start justify-between"><div><h3 className="font-semibold">{item.name || item.label || item.key}</h3><p className="mt-2 text-3xl font-semibold">{money(item.priceNgn * 100)}</p></div><CreditCard className="text-violet-300" size={20}/></div><p className="mt-4 text-sm text-zinc-400"><span className="text-white">{item.credits.toLocaleString()}</span> credits</p><button disabled={Boolean(busy)} onClick={() => purchase(item)} className="mt-5 w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-medium hover:bg-violet-500 disabled:opacity-50">{busy === item.key ? "Opening checkout…" : "Buy credits"}</button></article>)}</div> : <div className="rounded-2xl border border-dashed border-zinc-800 p-6 text-sm text-zinc-400"><p className="font-medium text-zinc-300">There are no upgrade packages available, so users cannot start checkout yet.</p><p className="mt-2">Add priced credit packages to the server’s <code className="text-violet-300">CREDIT_PACKAGES_JSON</code> setting. Once enabled, users select a package here and pay through Paystack.</p></div>}</section>
      <section className="grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border border-zinc-800 bg-zinc-900/40 p-5"><h2 className="text-lg font-semibold">Payment history</h2><div className="mt-4 divide-y divide-zinc-800">{payments.length ? payments.map((payment) => <div key={payment.id || payment.reference} className="flex items-center justify-between gap-4 py-3"><div className="min-w-0"><p className="truncate text-sm">{payment.packageKey || "Credit purchase"}</p><p className="mt-1 text-xs text-zinc-500">{new Date(payment.createdAt).toLocaleString()} · {payment.reference}</p></div><div className="text-right"><p className="text-sm">{money(payment.amountMinor, payment.currency || "NGN")}</p><p className={`mt-1 text-xs capitalize ${payment.status === "success" ? "text-emerald-300" : "text-zinc-500"}`}>{payment.status}</p></div></div>) : <p className="py-8 text-center text-sm text-zinc-500">No payments yet.</p>}</div></div><div className="rounded-2xl border border-zinc-800 bg-zinc-900/40 p-5"><h2 className="text-lg font-semibold">Credit activity</h2><div className="mt-4 divide-y divide-zinc-800">{transactions.length ? transactions.map((transaction) => <div key={transaction.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm">{transaction.reason || transaction.type}</p><p className="mt-1 text-xs text-zinc-500">{new Date(transaction.createdAt).toLocaleString()}</p></div><span className={`text-sm font-medium ${transaction.delta > 0 ? "text-emerald-300" : "text-zinc-300"}`}>{transaction.delta > 0 ? "+" : ""}{transaction.delta}</span></div>) : <p className="py-8 text-center text-sm text-zinc-500">No credit activity yet.</p>}</div></div></section>
      <p className="flex items-center gap-2 text-xs text-zinc-600"><Check size={14}/> Payment checkout is handled securely by Paystack.</p>
    </>}
  </div>;
}
