import { useEffect, useState } from "react";
import { ArrowRight, Clapperboard, FolderOpen, Image, Images, LoaderCircle, Sparkles, Users, Video } from "lucide-react";
import { Link } from "react-router-dom";
import api from "@/services/api";
import useAuth from "@/hooks/useAuth";

const tiles=[{label:"Projects",path:"/projects",icon:FolderOpen,key:"projects"},{label:"Images",path:"/images",icon:Image,key:"images"},{label:"Videos",path:"/videos",icon:Video,key:"videos"},{label:"Characters",path:"/characters",icon:Users,key:"characters"}];
const actions=[{label:"Generate image",path:"/generate",icon:Sparkles},{label:"Open projects",path:"/projects",icon:FolderOpen},{label:"Storyboard",path:"/storyboard",icon:Clapperboard},{label:"Creative library",path:"/gallery",icon:Images}];

export default function Dashboard(){
 const user=useAuth((s)=>s.user);const [data,setData]=useState({projects:[],images:[],videos:[],characters:[]});const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let live=true;(async()=>{try{const [p,i,v,c]=await Promise.all([api.get("/projects"),api.get("/images"),api.get("/videos"),api.get("/characters")]);if(live)setData({projects:p.data?.data?.projects||[],images:i.data?.data?.images||[],videos:v.data?.data?.videos||[],characters:c.data?.data?.characters||[]});}catch(e){if(live)setError(e.response?.data?.message||"Some workspace data could not be loaded.");}finally{if(live)setLoading(false);}})();return()=>{live=false};},[]);
 return <div data-tour="dashboard-overview" className="space-y-8 text-white"><section className="relative overflow-hidden rounded-3xl border border-violet-500/15 bg-gradient-to-br from-violet-950/50 via-zinc-900 to-zinc-950 p-6 sm:p-9"><div className="relative z-10 max-w-2xl"><p className="text-sm font-medium text-violet-300">Nebula AI Studio</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Welcome{user?.name?`, ${user.name.split(" ")[0]}`:""}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-400">Your creative workspace for images, video, characters, and stories. Continue a project or start with a new idea.</p><Link to="/generate" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold hover:bg-violet-500"><Sparkles size={17}/> Start creating</Link></div><div className="absolute -right-16 -top-24 h-72 w-72 rounded-full bg-fuchsia-600/10 blur-3xl"/></section>
 <section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Your workspace</h2><p className="mt-1 text-sm text-zinc-500">Live totals from your account</p></div>{loading&&<LoaderCircle size={18} className="animate-spin text-zinc-500"/>}</div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{tiles.map(({label,path,icon:Icon,key})=><Link key={key} to={path} className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4 transition hover:border-violet-500/40"><div className="flex items-center justify-between"><span className="text-sm text-zinc-400">{label}</span><Icon size={18} className="text-violet-400"/></div><p className="mt-3 text-2xl font-semibold">{loading?"—":data[key].length}</p></Link>)}</div>{error&&<p className="mt-3 text-sm text-amber-300">{error}</p>}</section>
 <section className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><div className="rounded-2xl border border-zinc-800 bg-zinc-900/40 p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Recent projects</h2><p className="mt-1 text-xs text-zinc-500">Pick up where you left off</p></div><Link to="/projects" className="text-xs text-violet-300">All projects <ArrowRight className="inline" size={13}/></Link></div>{data.projects.slice(0,5).map((p)=><Link key={p.id} to={`/projects/${p.id}/workspace`} className="flex items-center gap-3 border-t border-zinc-800/70 py-3"><FolderOpen size={18} className="text-violet-400"/><span className="min-w-0 flex-1 truncate text-sm">{p.name}</span><span className="text-xs text-zinc-600">{new Date(p.updatedAt||p.createdAt).toLocaleDateString()}</span></Link>)}{!loading&&!data.projects.length&&<p className="border-t border-zinc-800 py-8 text-center text-sm text-zinc-500">No projects yet. <Link to="/projects" className="text-violet-300">Create one</Link></p>}</div><div className="rounded-2xl border border-zinc-800 bg-zinc-900/40 p-5"><h2 className="font-semibold">Create and explore</h2><p className="mt-1 text-xs text-zinc-500">Open one of your creative tools</p><div className="mt-4 space-y-2">{actions.map(({label,path,icon:Icon})=><Link key={label} to={path} className="flex items-center gap-3 rounded-xl bg-zinc-950/70 p-3 text-sm text-zinc-300 hover:bg-zinc-800"><Icon size={17} className="text-violet-400"/>{label}<ArrowRight className="ml-auto text-zinc-600" size={15}/></Link>)}</div></div></section></div>
}
