import { useEffect, useMemo, useState } from "react";
import { Download, FileImage, FileVideo, LoaderCircle, Search } from "lucide-react";
import { getImages, getVideos } from "@/services/media";
import api from "@/services/api";

export default function Downloads(){
 const [files,setFiles]=useState([]);const [query,setQuery]=useState("");const [kind,setKind]=useState("all");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let live=true;(async()=>{try{const [images,videos]=await Promise.all([getImages(),getVideos()]);if(live)setFiles([...images.map((item)=>({...item,kind:"image"})),...videos.map((item)=>({...item,kind:"video"}))].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)));}catch(e){if(live)setError(e.response?.data?.message||"Could not load your files.");}finally{if(live)setLoading(false);}})();return()=>{live=false};},[]);
 const filtered=useMemo(()=>files.filter((f)=>(kind==="all"||f.kind===kind)&&(f.name||f.prompt||"").toLowerCase().includes(query.toLowerCase())),[files,query,kind]);
 return <div className="space-y-7 text-white"><header><p className="text-sm text-violet-400">File manager</p><h1 className="mt-2 text-3xl font-semibold">Downloads</h1><p className="mt-2 text-sm text-zinc-500">Download files you generated in your workspace.</p></header><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search files…" className="h-12 w-full rounded-xl border border-zinc-800 bg-zinc-900 pl-11 pr-4 text-sm outline-none focus:border-violet-500"/></div><select value={kind} onChange={(e)=>setKind(e.target.value)} className="h-12 rounded-xl border border-zinc-800 bg-zinc-900 px-4 text-sm"><option value="all">All files</option><option value="image">Images</option><option value="video">Videos</option></select></div>{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}{loading?<div className="flex justify-center py-20 text-zinc-500"><LoaderCircle className="animate-spin"/></div>:filtered.length?<div className="overflow-hidden rounded-2xl border border-zinc-800">{filtered.map((file)=><div key={`${file.kind}-${file.id}`} className="flex items-center gap-3 border-b border-zinc-800 bg-zinc-900/40 p-4 last:border-0"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-500/10 text-violet-300">{file.kind==="image"?<FileImage size={19}/>:<FileVideo size={19}/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{file.name||"Untitled " + file.kind}</p><p className="mt-1 text-xs text-zinc-500">{file.kind} · {new Date(file.createdAt).toLocaleString()}</p></div><a href={`${api.defaults.baseURL}/${file.kind === "image" ? "images" : "videos"}/${encodeURIComponent(file.id)}/download`} className="rounded-lg border border-zinc-700 p-2 text-zinc-300 hover:bg-zinc-800" aria-label={`Download ${file.name||file.kind}`}><Download size={17}/></a></div>)}</div>:<div className="rounded-2xl border border-dashed border-zinc-800 py-20 text-center"><Download size={30} className="mx-auto text-zinc-600"/><p className="mt-3 font-medium">No files to download yet</p><p className="mt-1 text-sm text-zinc-500">Generated media is listed here when saved to your account.</p></div>}</div>;
}
