import { useEffect, useMemo, useState } from "react";
import { Image as ImageIcon, LoaderCircle, Search } from "lucide-react";
import api from "@/services/api";

export default function Gallery() {
  const [items,setItems]=useState([]); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const reload=async()=>{try{const {data}=await api.get("/gallery");setItems(data?.data?.items||[]);setError("");}catch(e){setError(e.response?.data?.message||"Could not load your creative library.");}finally{setLoading(false);}};
  useEffect(()=>{let active=true;api.get("/gallery").then(({data})=>{if(active)setItems(data?.data?.items||[]);}).catch((e)=>{if(active)setError(e.response?.data?.message||"Could not load your creative library.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[]);
  const filtered=useMemo(()=>items.filter((item)=>(item.name||item.prompt||"").toLowerCase().includes(query.toLowerCase())),[items,query]);
  const urlOf=(item)=>item.url||item.imageUrl||item.thumbnailUrl;
  return <div className="space-y-7 text-white"><header><p className="text-sm text-violet-400">Creative library</p><h1 className="mt-2 text-3xl font-semibold">Gallery</h1><p className="mt-2 text-sm text-zinc-500">Images, characters, and assets saved to your account.</p></header><div className="relative"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search your library…" className="h-12 w-full rounded-xl border border-zinc-800 bg-zinc-900 pl-11 pr-4 text-sm outline-none focus:border-violet-500"/></div>{error&&<div role="alert" className="flex justify-between rounded-xl border border-red-500/20 p-4 text-sm text-red-300">{error}<button onClick={reload} className="underline">Retry</button></div>}{loading?<div className="flex justify-center py-20 text-zinc-500"><LoaderCircle className="animate-spin"/></div>:filtered.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map((item)=>{const url=urlOf(item);const name=item.name||item.title||"Untitled";return <article key={`${item.galleryType}-${item.id}`} className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900/60"><a href={url||"#"} target={url?"_blank":undefined} rel="noreferrer" className="grid aspect-[4/3] place-items-center bg-zinc-950">{url?<img src={item.thumbnailUrl||url} alt={name} loading="lazy" className="h-full w-full object-cover"/>:<ImageIcon size={32} className="text-zinc-700"/>}</a><div className="p-4"><p className="truncate text-sm font-medium">{name}</p><div className="mt-2 flex items-center justify-between text-xs text-zinc-500"><span>{item.galleryType||item.type||"Asset"}</span><span>{item.createdAt?new Date(item.createdAt).toLocaleDateString():""}</span></div></div></article>;})}</div>:<div className="rounded-2xl border border-dashed border-zinc-800 py-20 text-center"><ImageIcon size={32} className="mx-auto text-zinc-600"/><p className="mt-3 font-medium">{query?"No matching items":"Your gallery is empty"}</p><p className="mt-1 text-sm text-zinc-500">Assets saved from your projects will appear here.</p></div>}</div>;
}
