import { useEffect, useMemo, useState } from "react";
import { Download, LoaderCircle, Search, Trash2, Video as VideoIcon } from "lucide-react";
import { Link } from "react-router-dom";
import { deleteVideo, getVideos } from "@/services/media";
import api from "@/services/api";
import MediaViewer from "@/components/media/MediaViewer";

export default function Videos() {
  const [items, setItems] = useState([]); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [viewerIndex,setViewerIndex]=useState(null);
  const reload=async()=>{try{setItems(await getVideos());setError("");}catch(e){setError(e.response?.data?.message||"Could not load your videos.");}finally{setLoading(false);}};
  useEffect(()=>{let active=true;getVideos().then((data)=>{if(active)setItems(data);}).catch((e)=>{if(active)setError(e.response?.data?.message||"Could not load your videos.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[]);
  const filtered=useMemo(()=>items.filter(item=>(item.name||item.prompt||"").toLowerCase().includes(query.toLowerCase())),[items,query]);
  const remove=async(id)=>{try{await deleteVideo(id);setItems((old)=>old.filter((item)=>item.id!==id));}catch(e){setError(e.response?.data?.message||"Could not delete this video.");}};
  return <div className="space-y-7 text-white"><header className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-sm text-violet-400"><VideoIcon size={16}/> Creative library</div><h1 className="text-3xl font-semibold">Videos</h1><p className="mt-2 text-sm text-zinc-500">Your generated video projects.</p></div><Link to="/generate" className="rounded-xl bg-violet-600 px-4 py-3 text-sm font-medium hover:bg-violet-500">Open video workspace</Link></header>
  <div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500" size={18}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search your videos…" className="h-12 w-full rounded-xl border border-zinc-800 bg-zinc-900 pl-11 pr-4 text-sm outline-none focus:border-violet-500"/></div>
  {error&&<div role="alert" className="flex justify-between rounded-xl border border-red-500/20 p-4 text-sm text-red-300">{error}<button onClick={reload} className="underline">Retry</button></div>}
  {loading?<div className="flex justify-center py-20 text-zinc-500"><LoaderCircle className="animate-spin"/></div>:filtered.length?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((item,index)=><article key={item.id} className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900/70"><button type="button" onClick={()=>setViewerIndex(index)} className="group relative block aspect-video w-full bg-black"><video src={item.url} poster={item.thumbnailUrl||undefined} playsInline preload="none" muted className="h-full w-full object-contain" aria-label={`Open ${item.name||"generated video"}`}/><span className="absolute inset-0 grid place-items-center bg-black/0 text-white/0 transition group-hover:bg-black/20 group-hover:text-white">▶</span></button><div className="flex items-start justify-between gap-3 p-4"><div className="min-w-0"><h2 className="truncate text-sm font-medium">{item.name||"Untitled video"}</h2><p className="mt-1 line-clamp-2 text-xs text-zinc-500">{item.prompt||"No prompt saved"}</p></div><div className="flex shrink-0"><a href={`${api.defaults.baseURL}/videos/${encodeURIComponent(item.id)}/download`} className="rounded-lg p-2 text-zinc-400 hover:bg-zinc-800" aria-label="Download video"><Download size={16}/></a><button onClick={()=>remove(item.id)} className="rounded-lg p-2 text-zinc-400 hover:bg-zinc-800 hover:text-red-400" aria-label="Delete video"><Trash2 size={16}/></button></div></div></article>)}</div>:<div className="rounded-2xl border border-dashed border-zinc-800 py-20 text-center"><VideoIcon size={32} className="mx-auto text-zinc-600"/><p className="mt-3 font-medium">{query?"No matching videos":"No videos yet"}</p><p className="mt-1 text-sm text-zinc-500">Generated videos will appear here.</p></div>}
  {viewerIndex !== null && <MediaViewer items={filtered.map((item) => ({ ...item, type: "video" }))} index={viewerIndex} onClose={() => setViewerIndex(null)} onChange={setViewerIndex} getDownloadUrl={(item) => `${api.defaults.baseURL}/videos/${encodeURIComponent(item.id)}/download`} />}</div>;
}
