import { useEffect, useMemo, useState } from "react";
import { Clapperboard, LoaderCircle, Plus, Search, Trash2 } from "lucide-react";
import api from "@/services/api";

export default function Storyboard(){
 const [items,setItems]=useState([]);const [query,setQuery]=useState("");const [name,setName]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 const reload=async()=>{try{const {data}=await api.get("/storyboards");setItems(data?.data?.storyboards||[]);setError("");}catch(e){setError(e.response?.data?.message||"Could not load storyboards.");}finally{setLoading(false);}};
 useEffect(()=>{let active=true;api.get("/storyboards").then(({data})=>{if(active)setItems(data?.data?.storyboards||[]);}).catch((e)=>{if(active)setError(e.response?.data?.message||"Could not load storyboards.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[]);
 const filtered=useMemo(()=>items.filter((s)=>(s.name||"").toLowerCase().includes(query.toLowerCase())),[items,query]);
 const create=async(e)=>{e.preventDefault();if(name.trim().length<2)return;setSaving(true);setError("");try{const {data}=await api.post("/storyboards",{name:name.trim()});const created=data?.data?.storyboard;if(created)setItems((prev)=>[created,...prev]);setName("");}catch(e){setError(e.response?.data?.message||"Could not create storyboard.");}finally{setSaving(false);}};
 const remove=async(id)=>{try{await api.delete(`/storyboards/${id}`);setItems((prev)=>prev.filter((s)=>s.id!==id));}catch(e){setError(e.response?.data?.message||"Could not delete storyboard.");}};
 return <div className="space-y-7 text-white"><header><p className="text-sm text-violet-400">Story studio</p><h1 className="mt-2 text-3xl font-semibold">Storyboards</h1><p className="mt-2 text-sm text-zinc-500">Create and organize storyboards saved to your account.</p></header><form onSubmit={create} className="flex flex-col gap-3 rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4 sm:flex-row"><input required minLength={2} maxLength={200} value={name} onChange={(e)=>setName(e.target.value)} placeholder="Name your storyboard" className="h-11 min-w-0 flex-1 rounded-xl border border-zinc-800 bg-zinc-950 px-4 text-sm outline-none focus:border-violet-500"/><button disabled={saving} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 text-sm font-medium disabled:opacity-50"><Plus size={16}/>{saving?"Creating…":"New storyboard"}</button></form><div className="relative"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search storyboards…" className="h-12 w-full rounded-xl border border-zinc-800 bg-zinc-900 pl-11 pr-4 text-sm outline-none focus:border-violet-500"/></div>{error&&<div role="alert" className="flex justify-between rounded-xl border border-red-500/20 p-4 text-sm text-red-300">{error}<button onClick={reload} className="underline">Retry</button></div>}{loading?<div className="flex justify-center py-20 text-zinc-500"><LoaderCircle className="animate-spin"/></div>:filtered.length?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((item)=><article key={item.id} className="flex items-start gap-4 rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-violet-500/10 text-violet-300"><Clapperboard size={19}/></span><div className="min-w-0 flex-1"><h2 className="truncate font-medium">{item.name}</h2><p className="mt-1 text-xs text-zinc-500">{item.project?.name||"Personal storyboard"}</p><p className="mt-3 line-clamp-2 text-sm text-zinc-400">{item.description||"No description added."}</p><p className="mt-3 text-xs text-zinc-600">Updated {new Date(item.updatedAt||item.createdAt).toLocaleDateString()}</p></div><button onClick={()=>remove(item.id)} className="rounded-lg p-2 text-zinc-500 hover:bg-zinc-800 hover:text-red-400" aria-label={`Delete ${item.name}`}><Trash2 size={16}/></button></article>)}</div>:<div className="rounded-2xl border border-dashed border-zinc-800 py-20 text-center"><Clapperboard size={32} className="mx-auto text-zinc-600"/><p className="mt-3 font-medium">{query?"No matching storyboards":"No storyboards yet"}</p><p className="mt-1 text-sm text-zinc-500">Create a storyboard above to start planning a story.</p></div>}</div>;
}
